# Generated by Django 3.2.2 on 2021-05-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_auto_20210507_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_instructions',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
